using System;
using System . Collections . Generic;
using System . Linq;
using System . Text;
using System . Threading . Tasks;

namespace ClassAccessTest
{
	class stringhandler
	{

	// used for the creation of string resources to save space in source code files
		public static string [ ] LoadSQLValues ( )
		{
			string[] list2 = {
						" 0",
						"-1",
						"1",
						"14",
						"1",
						"1",
						"11",
						"12",
						"13",
						"2",
						"2",
						"2",
						"3",
						"3",
						"3",
						"4",
						"4",
						"4",
						"-1",
						"-4",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"-4",
						"-4",
						"6",
						"6",
						"6",
						"6",
						"6",
						"6",
						"6",
						"6",
						"-5",
						"-5",
						"7",
						"7",
						"-2",
						"-2",
						"-2",
						"-2",
						"8",
						"8",
						"8",
						"-3",
						"-3",
						"9",
						"9",
						"9",
						"9",
						"9",
						"9",
						"9",
						"-4",
						"-4",
						"10",
						"10",
						"10",
						"99",
						"99",
			};
			return list2;
		}

		public static string [ ] LoadSQLFields ( )
		{
			string[] commands = {
				"[DOUBLE CLICK ON ANY SELECTION]",
				"[Enter items one per line]",
				"Select",
				"Select *",
				"Select TOP 100",
				"Select TOP 250",
				"Select From Customer",
				"Select From BankAccount",
				"Select from SecondaryCustAccounts",
				"Insert into Customer (",
				"Insert into BankAccount (",
				"Insert into SecondaryCustAccounts (",
				"Update Customer (",
				"Update BankAccount (",
				"Update SecondaryCustAccounts (",
				"Alter Customer (",
				"Alter BankAccount (",
				"Alter SecondaryCustAccounts (",
				"",
				"[ CUSTOMER FIELDS ]",
				"CustomerNumber,",
				"FirstName,",
				"LastName,",
				"PhoneNumber,",
				"MobileNumber,",
				"Address1,",
				"Address2,",
				"Town,",
				"County,",
				"PostCode,",
				"DOB,",
				"FileName,",
				"FullFileName,",
				"SecAccounts,",
				"",
				"[ BANKACCOUNT FIELDS ]",
				"BankACNumber,",
				"CustACNumber,",
				"AccountType,",
				"Balance,",
				"OpenDate,",
				"CloseDate,",
				"InterestRate,",
				"Status,",
				"",
				"[ SECONDARYCUSTACCOUNTS ]",
				"AccountType,",
				"AccountNum,",
				"",
				"(ONLY Add this if you are Updating or inserting new data)",
				"&only AFTER you have entered ALL the fields to be displayed",
				"",
				"Values (",
				"",
				"(",
				"[ Select Function ( ) for (Value data entry eg : DOB = GetRandomSQLDate)]",
				"[ in correct sequence ]",
				"GetRandomSQLdate",
				"GetCustNumber",
				"GetBankNumber",
				"GetCustFileName",
				"GetBankFileName",
				"GetCustFullFileName",
				"GetBankFullFileName",
				"",
				"[ Add at the VERY END end of your ENQUIRY ( 'SELECT' only )",
				"from BankAccount",
				"from Customer",
				"from SecondaryCustAccounts",
				"",
				""
					};
			return commands;
		}
	}
}
